query allFilmsWithVariablesQuery($first: Int!) {
  allFilms(first: $first) {
    films {
      id
      title
      openingCrawl
      created
    }
  }
}

query fetchFilmWithVariablesQuery($id: ID!) {
  film(id: $id) {
    id
    title
    openingCrawl
    created
  }
}
