name: Tests
on:
  pull_request:
    branches: [main, master]

jobs:
  test:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: volta-cli/action@v4

      - name: Install node
        run: volta install node

      - name: Install pnpm
        run: volta install pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Unit Test
        run: pnpm test:unit

      - name: E2E Test
        run: pnpm exec playwright test --ignore-snapshots

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
