name: Update-VRT
on: 
  workflow_dispatch:

env:
  VOLTA_FEATURE_PNPM: 1
  WEB_ENDPOINT: http://localhost:3000

jobs:
  test:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.38.1-jammy
    steps:
      - uses: actions/checkout@v3

      - uses: volta-cli/action@v4

      - name: Install node
        run: volta install node

      - name: Install pnpm
        run: volta install pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps

      - name: Set Env
        run: cp .sample.env .env

      - name: E2E Test
        run: pnpm exec playwright test --update-snapshots

      - name: Diff
        id: diff
        run: |
          git add -N .
          git diff --name-only --exit-code
        continue-on-error: true
      - name: Commit & Push
        run: |
          set -x
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add .
          git commit --author=. -m 'generated'
          git push
        if: steps.diff.outcome == 'failure'

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
